function [] = fc_Frictionforce()
% FC_FRICTIONFORCE - Computes friction force, torque, and forces for a system.
% This function calls multiple sub-functions to initialize parameters, compute forces,
% calculate torque, and finally determine the frictional forces.

    global Parameters Forces Torque Friction

    % Step 1: Initialize constant parameters
    Parameters = fc_Constant_Parameters(); 
    
    % Step 2: Compute additional calculation parameters based on constants
    Parameters = fc_Calculation_Parameters(Parameters);

    % Step 3: Calculate forces acting on the system
    Forces = fc_forces(Parameters); 

    % Step 4: Compute the torque generated by the system
    Torque = fc_Torque(Parameters, Forces);

    % Step 5: Compute the frictional forces based on parameters, forces, and torque
    Friction = fc_friction(Parameters, Forces, Torque);

end
