function Friction = fc_friction (Parameters, Forces, Torque)
% FC_FRICTION - Computes the friction forces and torques in a ball-screw system.
% This function calculates the tangential contact forces, friction torques, and
% total friction forces acting on both the screw and nut.

    %% Total Tangential Force Between a Ball and the Screw (FS)
    % FS is the algebraic sum of the tangential contact forces in the rolling direction.
    % Reference: "A new model to estimate friction torque in a ball screw system"
    Friction.force.FS = ((Torque.MC.Nut + Torque.MC.Screw + Torque.MER.Nut + Torque.MER.Screw + Torque.MB) / Parameters.Geometry.D_Ball) + ...
                        (Forces.FR.Nut + Forces.FR.Screw) + ...
                        (((Forces.FR.Nut + Forces.FR.Screw) * Parameters.Geometry.D_Ball * cosd(Parameters.Geometry.AngleContact)) / Parameters.Geometry.D_Screw) + ...
                        (Forces.FB / 2);

    %% Total Tangential Force Between a Ball and the Nut (FN)
    % FN is the algebraic sum of the tangential contact forces in the rolling direction.
    % Reference: "A new model to estimate friction torque in a ball screw system"
    Friction.force.FN = ((Torque.MC.Nut + Torque.MC.Screw + Torque.MER.Nut + Torque.MER.Screw + Torque.MB) / Parameters.Geometry.D_Ball) + ...
                        (Forces.FR.Nut + Forces.FR.Screw) - ...
                        (((Forces.FR.Nut + Forces.FR.Screw) * Parameters.Geometry.D_Ball * cosd(Parameters.Geometry.AngleContact)) / Parameters.Geometry.D_Screw) - ...
                        (Forces.FB / 2);

    %% Ball-Screw Contact Radius (Rs)
    % Rs is the radius of the ball-screw contact point.
    Friction.Radius.Screw = (Parameters.Geometry.D_Screw / 2) - (Parameters.Geometry.D_Ball * cosd(Parameters.Geometry.AngleContact) / 2);

    %% Ball-Nut Contact Radius (Rn)
    % Rn is the radius of the ball-nut contact point.
    Friction.Radius.Nut = (Parameters.Geometry.D_Screw / 2) + (Parameters.Geometry.D_Ball * cosd(Parameters.Geometry.AngleContact) / 2);

    %% Friction Torque Generated by a Ball-Screw Contact
    % Computed as the product of force FS and the screw contact radius.
    Friction.Torque.Screw = Friction.force.FS * Friction.Radius.Screw;

    %% Friction Torque Generated by a Ball-Nut Contact
    % Computed as the product of force FN and the nut contact radius.
    Friction.Torque.Nut = Friction.force.FN * Friction.Radius.Nut;

    %% Total Friction Torque Acting on the Screw
    % Summing friction torques in all ball-screw contacts.
    Friction.All_Torque.Screw = Parameters.Geometry.BallNumber * Friction.Torque.Screw;

    %% Total Friction Torque Acting on the Nut
    % Summing friction torques in all ball-nut contacts.
    Friction.All_Torque.Nut = Parameters.Geometry.BallNumber * Friction.Torque.Nut;

    %% Total Friction Force Acting on the Screw
    % Summing friction forces in all ball-screw contacts.
    Friction.All_Force.Screw = Parameters.Geometry.BallNumber * Friction.force.FS;

    %% Total Friction Force Acting on the Nut
    % Summing friction forces in all ball-nut contacts.
    Friction.All_Force.Nut = Parameters.Geometry.BallNumber * Friction.force.FN;

end
